[start]
command:/usr/local/etc/rc.d/mihomo start
parameters:
type:script
message:starting mihomo

[stop]
command:/usr/local/etc/rc.d/mihomo stop
parameters:
type:script
message:stopping mihomo

[restart]
command:/usr/local/etc/rc.d/mihomo restart
parameters:
type:script
message:restarting mihomo
description:Restart mihomo service

[status]
command:/usr/local/etc/rc.d/mihomo status; exit 0
parameters:
type:script_output
message:request mihomo status

[health]
command:/usr/local/opnsense/scripts/mihomo/health.sh
parameters:
type:script
message:checking mihomo health
description:Mihomo health check
