###################################################################
# Local syslog-ng configuration filter definition [mihomo].
###################################################################
filter f_local_mihomo {
    program("mihomo");
};
