name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *"
  push:
    branches:
      - master
      - hidden
    paths-ignore:
      - "**/README.md"
      - "**/template.yaml"

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 6

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { goos: freebsd, goarch: riscv64 }
          - { goos: freebsd, goarch: amd64 }
          - { goos: freebsd, goarch: 386 }
          - { goos: freebsd, goarch: arm, goarm: 6 }
          - { goos: freebsd, goarch: arm, goarm: 7 }
          - { goos: freebsd, goarch: arm64 }
    outputs:
      NEW: ${{ steps.check.outputs.NEW }}
      VERSION: ${{ steps.check.outputs.VERSION }}

    steps:
      - name: Checkout the "hidden" branch
        uses: actions/checkout@v6
        with:
          ref: hidden

      - name: Calculate latest version
        run: |
          LATEST_VERSION=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name' | sed 's|v||g')
          if [ "${LATEST_VERSION}" == "null" ]; then
            echo "wrong version"
            exit 1
          fi
          echo "RELEASE_NAME=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "TAG_NAME=v${LATEST_VERSION}" >> $GITHUB_ENV
          echo "TAGS=with_gvisor" >> $GITHUB_ENV
          echo "VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
        shell: bash

      - name: Check for new version
        id: check
        run: |
          if [ -f last_version ]; then
            LAST_VERSION=$(cat last_version)
          else
            LAST_VERSION="none"
          fi
          echo "Last version: ${LAST_VERSION}, current version: ${{ env.VERSION }}"
          if [ "${{ env.VERSION }}" != "${LAST_VERSION}" ]; then
            echo "NEW=true" >> $GITHUB_ENV
            echo "NEW=true" >> $GITHUB_OUTPUT
          else
            echo "NEW=false" >> $GITHUB_ENV
            echo "NEW=false" >> $GITHUB_OUTPUT
          fi
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Download and extract source tarball files
        if: github.event_name != 'schedule' || env.NEW == 'true'
        run: |
          wget https://github.com/MetaCubeX/mihomo/archive/refs/tags/v${{ env.VERSION }}.tar.gz -O mihomo-${{ env.VERSION }}.tar.gz
          tar -xf mihomo-${{ env.VERSION }}.tar.gz && mv mihomo-${{ env.VERSION }} mihomo
          ls -lha

      - name: Apply patches
        if: github.event_name != 'schedule' || env.NEW == 'true'
        run: |
          cd mihomo
          cp component/memory/memory_freebsd_amd64.go component/memory/memory_freebsd_riscv64.go
          patch -p1 < ../mihomo.patch

      - name: Setup go
        if: github.event_name != 'schedule' || env.NEW == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Cache go dependencies
        if: github.event_name != 'schedule' || env.NEW == 'true'
        uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Cache go build (not arm)
        if: matrix.goarch != 'arm' && github.event_name != 'schedule'
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Cache go build (arm)
        if: matrix.goarch == 'arm' && github.event_name != 'schedule'
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}

      - name: Build and compress binary file
        if: github.event_name != 'schedule' || env.NEW == 'true'
        run: |
          cd mihomo
          go build -v -tags ${{ env.TAGS }} -trimpath -ldflags '-X "github.com/metacubex/mihomo/constant.Version=${{ env.RELEASE_NAME }}" -X "github.com/metacubex/mihomo/constant.BuildTime=none" -w -s -buildid=' -o mihomo
          if [ "${{ matrix.goarch }}" == 'arm' ]; then
            mv mihomo clash-meta-${{ matrix.goos }}-${{ matrix.goarch }}v${{ matrix.goarm }}
            xz -v clash-meta-${{ matrix.goos }}-${{ matrix.goarch }}v${{ matrix.goarm }}
          else
            mv mihomo clash-meta-${{ matrix.goos }}-${{ matrix.goarch }}
            xz -v clash-meta-${{ matrix.goos }}-${{ matrix.goarch }}
          fi
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: 0

      - name: Move file to publish directory
        if: github.event_name != 'schedule' || env.NEW == 'true'
        run: |
          mkdir -p publish
          cp -v mihomo/clash-meta-* publish/

      - name: Release and upload assets
        if: github.event_name != 'schedule' || env.NEW == 'true'
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push:
    runs-on: ubuntu-latest
    if: needs.build.outputs.NEW == 'true'
    needs:
      - build
    steps:
      - name: Checkout the "hidden" branch
        uses: actions/checkout@v6
        with:
          ref: hidden

      - name: Update last_version
        run: |
          echo "${{ needs.build.outputs.VERSION }}" > last_version

      - name: Push last_version to "hidden" branch
        run: |
          git config --local user.name "Vincent Loeng"
          git config --local user.email "173226116+Vincent-Loeng@users.noreply.github.com"
          git add last_version
          git commit -m "Release ${{ needs.build.outputs.VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
